### PR TITLE
Allowed use of multiple prefixes with order in file

### PR DESCRIPTION
**Pull request by LordRalex**
Just the same pull, just that I got git worked out for future pulls. This also just has the changed to the 1 file that actually needed the changes.

### CODE REVIEW

**Comment by t3hk0d3** [comment]
Why just don't <code>prefix-&lt;groupname&gt;</code> and <code>prefix-all</code> ?

**Comment by LordRalex** [comment]
For what? Just got a little confused by your statement? Where would that be?

**Comment by Psithief** [comment]
Could you post an example permissions.yml for this pull request?

**Comment by LordRalex** [comment]
@Psithief 

My way is not affecting the permissions.yml, in fact it is affecting the ChatManager config.yml

I will have to get the layout though, sec

<pre>message-format:
global-message-format: '$prefix$player%suffix: %message'
ranged-mode: false
chat-range: 100
display-name-format: '%prefix%displayname%suffix'
override:
    main-group: false
    suffix-order: true
    prefixes: true
    suffixes: true
buffer:
    prefix:
        before: false
        middle: true
        after: true
    suffix:
        before: false
        middle: true
        after: true</pre>

**Comment by Psithief** [comment]
I see. Well, t3hk0d3 was suggesting you implement different permissions nodes instead of configuration nodes. I agree it seems simpler to have prefixes that will combine with others using a separate node string.

Or perhaps you could have each group set a `prefix-weight` and `suffix-weight` (numerical) node so that the prefixes and suffixes have a calculated order.

**Comment by LordRalex** [comment]
Well, this was just a temp solution that I had for a server since they were using classes but wanted staff to still participate, so I just made this, and decided to PR it. Although I have lost this code from numerous OS resets, I now see what was meant.

If i get a better one made, I will just do a new PR and close this one.

**Comment by LordRalex** [comment]
Completely redone it, and to prevent commit spam, closing this one

**Comment by Psithief** [comment]
@LordRalex Nice, how many branches? :D

**Comment by LordRalex** [comment]
New PR: https://github.com/PEXPlugins/ChatManager/pull/22

**Pull request closed without merging**
