### PR TITLE
Add Multiverse Colored world Aliases

### PR DESCRIPTION
**Pull request by fernferret**
All i've done is added a Soft Dependency (tested with and without Multiverse-Core.jar) of Multiverse to allow users to set an alias in Multiverse (so it shows up pretty in `/mv who` and `/mv list`) and it will now use this colored string if someone adds `%world` in their ChatManager config. Here is a sample config of it working:

```
chat-range: 100.0
global-message-format: <%prefix%player%suffix> &e%message
enable: true
message-format: '[%world]<%prefix%player%suffix> &e%message'
ranged-mode: false
display-name-format: '%prefix%player%suffix'
```

### CODE REVIEW

**Comment by mattdholloway** [comment]
Has this been done?

**Comment by fernferret** [comment]
I spoke with the author in IRC, and he told me that he has a complete rewrite of this plugin in the works. I have a build that will work for the meantime if you would like it (you can always build yourself off of my branch if you know how to use maven). He did not have an ETA for completion.

**Comment by mattdholloway** [comment]
I have PEX running, what can I do?

**Comment by fernferret** [comment]
Install this Plugin (ChatManager) but the version provided by the original author will not support MV2 aliases, however, the code in this pull request does. I will get a link up to an unofficial version until the next gen of this plugin is completed.

**Comment by dionrhys** [comment]
Implemented manually in https://github.com/PEXPlugins/ChatManager/commit/47f1f1a0549a8e1c1930a375464e51ff0306a0ba.

Thank you for contributing :)

**Pull request closed without merging**
