### PR TITLE
Prefix

### PR DESCRIPTION
**Pull request by LordRalex**
Contains the code for the multiple prefixes. Just what I did to do it really.

### CODE REVIEW

**Comment by dionrhys** [comment]
I'm not able to test at the moment, but does this work with the user's specific prefix?

```
users:
..Didz:
....groups:
....- Admin
....options:
......prefix: "[Dev]"
```

(Ignore the dots)
It seems to be only getting the prefix from the groups?

**Comment by LordRalex** [comment]
I don't think in your format it will since AKAIK pex just puts prefix, not the option part. And so the code should work for that. So your file, no, since it is not following the regular pex settings

users:
  Lord_Ralex:
    group:
    - Admin
    prefix: 'Hi'

should work since i called the getPrefix(), although the getOwnPrefix() might be more appropriate
i am using my phone atm so i cannot check it well.

---Original Message---

**Comment by LordRalex** [comment]
This is from what I understand of PEX and how it works, and that is how I have my files and it works fine with those.

**Comment by LordRalex** [comment]
Made a new one with this, it is what i had changed and what needed to be changed

**Pull request closed without merging**
